In [3]:
import numpy as np

In [8]:
def minimise_1d(f, loss_fn, x, lr=0.01, max_iter=1000, eps=0.001):
    xs = [x]
    losses = []
    
    for i in range(max_iter):
        loss = loss_fn(x)
        losses.append(loss)
        
        if abs(loss) <= eps:
            break
        
        x -= lr * loss
        
        if abs(x - xs[-1]) <= eps:
            break
        
        xs.append(x)
        
    return xs, losses

In [113]:
def minimise(f, df, x, lr=0.01, max_iter=1000, eps=0.001):
    xs = [x]
    grads = []
    
    for i in range(max_iter):
        grad = df(x)
        grads.append(grad)
        
        if np.linalg.norm(grad) <= eps:
            break
            
        x = xs[-1] - grad * lr
#         print(x)
        
        if abs(f(x) - f(xs[-1])) <= eps:
#             print("delta f(x):", abs(f(x) - f(xs[-1])))
            break
        
        xs.append(x)
        
    return xs, grads    

In [117]:
f = lambda x: (x[0] - 200)**2 + (x[1] - 3)**2 + 10
loss_fn = lambda x: 2 * (x - np.array([200,3]))

In [182]:
xs, grads = minimise(f, loss_fn, np.array([0,0]), eps=1e-6, lr=0.01, max_iter=10_000)

delta f(x): 9.70810900113861e-07


In [5]:
rng = np.random.default_rng(seed=1234)

In [6]:
n, p = 1000, 1

In [90]:
X = np.random.normal(scale=5.0, size=(n,1))

In [92]:
mat = np.hstack([np.ones((n,1)), X])

In [93]:
eps = rng.normal(size=1000)

In [94]:
# beta = np.array([3.0, 1.5, 2.3])
beta = np.array([3.0, 1.5])

In [95]:
y = mat.dot(beta) + eps

In [96]:
np.mean((y - mat.dot(beta))**2)

0.9664482122568584

In [97]:
def MSE(beta, X, y):
    preds = X.dot(beta)
    return np.mean((y - preds)**2)

In [98]:
MSE(beta, mat, y)

0.9664482122568584

In [99]:
def MSE_grad(beta, X, y):
    preds = X.dot(beta)
    return 2 * (preds - y).dot(X)

In [66]:
# X = np.array([[1.4,2.3],[1.2,1.7]])
# X = np.hstack([np.ones((2,1)), X])
# beta = np.array([1.2, 2.3, 2.6])
# preds = X.dot(beta)
# y = np.array([7.2,6.95])
# (preds - y).dot(X)
# sum(X[:,2] * (preds - y)), MSE_grad(beta, X, y), 1.4 * 3.2, 1.2 * 1.43

In [137]:
betas, grads = minimise(
    lambda beta: MSE(beta, mat, y),
    lambda beta: MSE_grad(beta, mat, y),
    x=np.zeros(2), lr=1e-5, eps=1e-10, max_iter=100_000)
print('beta_min:', betas[-1]) 
print('grad norm', np.linalg.norm(grads[-1]))

beta_min: [2.99332369 1.50547633]
grad norm 0.09889053342759384


In [118]:
MSE(betas[-1], mat, y)

0.9656477179664247

In [129]:
grad_beta_hat = MSE_grad(beta_hat, mat, y)
grad_beta_hat, np.linalg.norm(grad_beta_hat)

(array([-4.48974191e-13, -1.26719746e-11]), 1.2679925772652768e-11)

In [133]:
MSE(beta_hat, mat, y)

0.9656225353194862

In [136]:
MSE_grad(betas[-1], mat, y)

array([-0.09888742, -0.00078416])

In [105]:
beta_hat_1 = (y - np.mean(y)).dot(X - np.mean(X)) / np.sum((X - np.mean(X))**2)
beta_hat_1

array([1.50547672])

In [108]:
beta_hat_0 = np.mean(y) - beta_hat_1 * np.mean(X)
beta_hat_0

array([2.99337321])

In [127]:
beta_hat = np.hstack([beta_hat_0, beta_hat_1])
beta_hat

array([2.99337321, 1.50547672])

In [100]:
((X - np.mean(X)) * (y - np.mean(y))).shape

(1000, 1000)

In [106]:
np.mean(X)

-0.19501978016962582

In [76]:
(X[1] - np.mean(X)) * (y[1] - np.mean(y)) 

array([1.73801384])

In [80]:
(X - np.mean(X)).shape

(1000, 1)

In [81]:
(y - np.mean(y)).shape

(1000,)

In [78]:
X.shape

(1000, 1)

In [69]:
np.sum((X - np.mean(X))**2)

26148.14366890816

In [70]:
np.sum((X - np.mean(X)) * (y - np.mean(y))) / np.sum((X - np.mean(X))**2)

1.018165896119345e-16

In [45]:
X = np.array([1.4,3.5])
y = np.array([7.2,6.95])

In [49]:
X - np.mean(X), y - np.mean(y)

(array([-1.05,  1.05]), array([ 0.125, -0.125]))

In [52]:
np.sum((X - np.mean(X)) * (y - np.mean(y)))

-0.2625

In [56]:
np.sum((X - np.mean(X))**2)

2.205